#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source ${SCRIPT_DIR}/vars

cmd="docker-compose -f ${SCRIPT_DIR}/docker-compose.yml -p ${PROJECT_NAME} down --remove-orphans"

if [ $# -gt 1 ]; then
  echo "Expected no params or only '--purge' param, but $# params given"
  exit 1
fi

if [ "$1" == "--purge" ]; then
  $cmd -v --rmi local
  rm -rf $PGDATA_DIR
  echo "Postgres was stopped and purged"
else
  $cmd
  echo "Postgres was stopped and kepped"
fi
