#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_DIR="$( dirname "${SCRIPT_DIR}" )"

export PROJECT_NAME="admin_zone_1"

export UID=`id -u` 2>/dev/null
export GID=`id -g`
export PG_PORT="${PG_PORT:-5432}"
export POSTGRES_DB=${PROJECT_NAME}_dev

export PGDATA_DIR=${SCRIPT_DIR}/pgdata